### ISSUE TITLE
About Us

### ISSUE THREAD

**Issue by manojkmohan** [osmkerala/osmkerala.github.io#1]
Need to improve

**Comment by manojkmohan** [comment]
https://github.com/osmkerala/osmkerala-tasks/issues/4

**Comment by naveenpf** [comment]
https://hackmd.io/@manojkmohan/BJa-7-cWP/edit

Closing tasks 4 (osmkerala/osmkerala-tasks#4) . Since it is related to website.

**Comment by naveenpf** [comment]
Already done. closing this.
