### ISSUE TITLE
Create a page for OSMGeoWeek

### ISSUE THREAD

**Issue by naveenpf** [osmkerala/osmkerala.github.io#23]
Please create a page for https://kerala.openstreetmap.in/osmgeoweek

**Comment by joicemjoseph** [comment]
Can you please add what content has to be added ?

**Comment by naveenpf** [comment]
OpenStreetMap Geography Awareness Week, or OSMGeoWeek for short, is an annual celebration of open mapping that takes place each November. OSM community members host in-person and virtual events to showcase the power of crowdsourced mapping and invite new mappers into the fold

**Comment by naveenpf** [comment]
https://docs.google.com/forms/d/e/1FAIpQLSfDizLrHUUNzELS6MREtXVV6uhPtChr0YfbwQg7JjVbzhENSA/viewform?usp=sf_link

**Comment by joicemjoseph** [comment]
https://kerala.openstreetmap.in/geoweek/ this is live.
