### ISSUE TITLE
Building OSM Kerala Community 

### ISSUE THREAD

**Issue by manojkmohan** [osmkerala/osmkerala.github.io#5]
Page created to edit attribution of OSM Kerala in Mapathon Kerala project  https://etherpad.wikimedia.org/p/Mapathon_kerala

**Comment by naveenpf** [comment]
https://hackmd.io/3xTPG2jJR06jQCy9YDZkpQ?view

**Comment by manojkmohan** [comment]
https://kerala.openstreetmap.in/building-osm-kerala-community/

**Comment by manojkmohan** [comment]
https://github.com/osmkerala/osmkerala.github.io/commit/be0d76af7086f10f197f0e755787347b121d28fe

**Comment by manojkmohan** [comment]
Hyperlinking and photo adding task in pedning

**Comment by naveenpf** [comment]
It is done.
